# Generated by Django 4.1.7 on 2024-09-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('last_name', models.CharField(max_length=50, verbose_name='名字')),
                ('first_name', models.CharField(max_length=50, verbose_name='名前')),
                ('age_group', models.CharField(max_length=2, verbose_name='年代')),
                ('gender', models.CharField(max_length=1, verbose_name='性別')),
                ('department_cd', models.CharField(max_length=10, verbose_name='所属部署CD')),
            ],
        ),
    ]
