# Generated by Django 5.1.2 on 2024-10-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'エリア',
                'verbose_name_plural': 'エリア',
                'db_table': 'Area_info',
            },
        ),
        migrations.CreateModel(
            name='AreaStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.PositiveIntegerField()),
                ('store_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'エリア店舗',
                'verbose_name_plural': 'エリア店舗',
                'db_table': 'Area_Store',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=15)),
                ('menu', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('business_hours', models.CharField(max_length=100)),
                ('map_link', models.URLField(blank=True, max_length=300, null=True)),
                ('payment_methods', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'db_table': 'Store_info',
            },
        ),
    ]
