# Generated by Django 5.1.2 on 2024-10-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='map_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='地図リンク'),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(),
        ),
    ]
