# Generated by Django 4.1.7 on 2024-09-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre_info',
        ),
    ]
