# Generated by Django 4.1.7 on 2024-09-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_genre_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
