# Generated by Django 4.1.7 on 2024-09-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Area_info',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=15)),
                ('menu', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('business_hours', models.CharField(max_length=100)),
                ('map_link', models.URLField(blank=True, max_length=300, null=True)),
                ('payment_methods', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Store_info',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Tag_info',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
    ]
