# Generated by Django 4.1.7 on 2024-09-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_area_store_tag_alter_userinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='users_info',
        ),
    ]
