# Generated by Django 4.1.7 on 2024-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名字')),
                ('last_name', models.CharField(max_length=50, verbose_name='名前')),
                ('age_group', models.CharField(max_length=2, verbose_name='年代')),
                ('gender', models.CharField(max_length=1, verbose_name='性別')),
                ('department_cd', models.CharField(max_length=10, verbose_name='所属部署CD')),
            ],
            options={
                'db_table': 'users_info',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
