# Generated by Django 5.1.2 on 2024-10-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userinfo_delete_usersinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'エリア', 'verbose_name_plural': 'エリア'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店舗', 'verbose_name_plural': '店舗'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
    ]
